### ISSUE TITLE
ConsoleOutputHandler SPELL_DELAY is too slow

### ISSUE THREAD

**Issue by liam027** [Veradux/wwa#13]
**This is a beginner issue for someone not familiar with Git workflow to learn how to do a branch, pull request etc! If you're brand new take this one on!**

ConsoleOutputHandler SPELL_DELAY is painfully slow when typing out long messages. Decrease it to something more reasonable.

```

public class ConsoleOutputHandler{

    private static final long SPELL_DELAY = 30;
```

**Comment by Veradux** [comment]
You mean that it has to be decreased, not increased, correct?

**Comment by liam027** [comment]
Fixed.

**Comment by AdamPhilipSmith** [comment]
Updated SPELL_DELAY to 15.
